services:
  web:
    build: .
    container_name: gelecegin-adanasi
    restart: unless-stopped
    ports:
      - "3007:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gelecegin-adanasi.rule=Host(`geleceginadanasi.org`)"
      - "traefik.http.routers.gelecegin-adanasi.entrypoints=websecure"
      - "traefik.http.routers.gelecegin-adanasi.tls.certresolver=letsencrypt"
      - "traefik.http.services.gelecegin-adanasi.loadbalancer.server.port=3000"
    networks:
      - proxy

networks:
  proxy:
    external: true
